### ISSUE TITLE
Some code verification

### ISSUE THREAD

**Issue by ClaudioLucioLopes** [galtay/hilbertcurve#17]
I am using this code, and in my point of view that is some strange in this case

p = 12; N = 3
hilbert_curve = HilbertCurve(p, N)

hilbert_curve.distance_from_coordinates(np.asarray([999,999,999]))
           766935405
hilbert_curve.distance_from_coordinates(np.asarray([479, 724, 495]))
           975605184

Does this result correct?
I wait that this point in 3d ([999,999,999]) was greater than  ([479, 724, 495])

**Comment by galtay** [comment]
I think we can answer your concern by looking at the image in the README.rst file (called "n2_p3.png").  Note that the distance along the curve does not always increase with coordinate values.  Specifically, for p=3, N=2, the coordinate values on each axis run from 0 to 7.  In the upper right corner the coordinates are [7,7] and the distance along the curve is 42.  This is about 3/4 of the way along the curve.  Every point after that will be further along the curve but will have coordinates that are equal to or smaller than [7,7].  Hope that helps, let me know if you have any questions. 

![n2_p3](https://user-images.githubusercontent.com/663051/57883367-fdc7d180-77f3-11e9-9ea4-6d1e4a601982.png)
