### ISSUE TITLE
A question for coordinates

### ISSUE THREAD

**Issue by zf6578** [galtay/hilbertcurve#19]
Hi，
I am new to this project and i want to use it,however,i met a question when i use function distance_from_coordinates(),the wrong code is '''if x[i] & Q', i use geo coordinates as input data,Q=1024 ,and it comes:TypeError: unsupported operand type(s) for &: 'float' and 'int'.
the input coordinates must be integer? is there have some method to deal with this?

**Comment by galtay** [comment]
Hi wangzi6578, 
You are correct.  The coordinates (input and output) are always integers in this implementation.  It is possible to define various projections onto the curve from floating point coordinates or floating point distance along the curve, but that is not implemented in this package. 
best, 
-Gabriel
