### ISSUE TITLE
Include LICENSE in published source distribution

### ISSUE THREAD

**Issue by mbargull** [galtay/hilbertcurve#20]
It is not possible to redistribute the published source tarballs from https://pypi.org/project/hilbertcurve/ without violating the license conditions
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
unless one obtains `LICENSE` separately from this repository or the `.whl`.

It would be helpful if you would include `LICENSE` in the source distributions too.
This can be done by adding either
- a `setup.cfg` file with contents
  ```
  [metadata]
  license_file = LICESE
  ```
  (This requires a somewhat recent version of `setuptools`), or
- a `MANIFEST.in` file with contents
  ```
  include LICENSE
  ```

**Comment by galtay** [comment]
thanks for the notice.  I'll add the MANIFEST.in

**Comment by galtay** [comment]
I think I managed to get a new pypi release up (v1.0.3) with the LICENSE file included (also removed the :math: directive from the readme.rst so it would render) https://pypi.org/project/hilbertcurve/1.0.3/

**Comment by mbargull** [comment]
Perfect, thanks!
