### ISSUE TITLE
Version installed with "pip install hilbertcurve" is out of date

### ISSUE THREAD

**Issue by alicehayes** [galtay/hilbertcurve#23]
The package installed by pip aka the package here: https://pypi.org/project/hilbertcurve/ is severely out of date. I installed it on my system and encountered an error with int type. It has been fixed in this repository but the last time the PyPI project was updated was last year so using "pip install hilbertcurve" downloads a flawed version of the library. Sorry if this is the wrong place, but I didn't see a place to report a problem on pypi.org

**Comment by alicehayes** [comment]
Turns out the issue (input validation/conversion) had not actually been fixed. I have made the necessary changes and issued a pull request. The problem that the package is out of date on pypi.org remains though.

**Comment by galtay** [comment]
thanks for the heads up! I've just updated the pypi package. lets get these updates merged and I'll update it again

**Comment by galtay** [comment]
closing this as the pypi issue is fixed, but will continue looking at #25
