### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by edent** [galtay/hilbertcurve#41]
The documentation at https://hilbertcurve.readthedocs.io/en/latest/readme.html still refers to `coordinates_from_distance`

I suspect this is because the branch `master` has been renamed to `main` - because going to edit the page via Read The Docs gives the error "Branch not found, redirected to default branch."

I think this is something the maintainer needs to change in the Read The Docs control panel.

Thanks for a great library - incredibly useful!

**Comment by galtay** [comment]
Thanks for the issue @edent ! I think I'll just delete the readthedocs site as all of the info is in the github README and on PyPI and it just means one less thing to maintain.
