### ISSUE TITLE
distance_from_coordinates method modifies value of input variable

### ISSUE THREAD

**Issue by kirit93** [galtay/hilbertcurve#8]
```
N               = 2
p               = 5
hilbert_curve   = hlb.HilbertCurve(p, N)

coords          = [3, 1]
distance        = hilbert_curve.distance_from_coordinates(coords)
x               = hilbert_curve.coordinates_from_distance(distance)
print("Coords   : ", coords)
print("Distance : ", distance)
print("x        : ", x)
```

Output:
```
Coords   :  [1, 2]
Distance :  6
x        :  [3, 1]
```

The encoded distance does not produce the correct coordinates while decoding. The tests written only check that 

Is there a problem with the ```distance_from_coordinates``` function?

**Comment by galtay** [comment]
Looks like `distance_from_coordinates` is modifying the value of `coords`.  I'll fix this.

**Comment by kirit93** [comment]
Adding the following to the ```distance_from_coordinates``` function solves the problem - 
```
if isinstance(coords, npy.ndarray):
            x   = coords.tolist()
        else:
            x   = coords
```

**Comment by galtay** [comment]
you're snippet probably worked b/c when you have an instance of numpy array and you call `tolist` you get a new object (and therefore don't modify the input).  the problem would have remained for input that wasn't numpy arrays though.  the PR I merged simply makes a copy of the input and operates on that. should fix your use case too.  let me know if you get strange results.  thanks for creating an issue!
